services:
  web:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - ./workspace:/workspace
      - ./scripts:/scripts:ro
      - ./seed:/seed:ro
    environment:
      - NG_CLI_ANALYTICS=false
      - CI=true
    command: ["/bin/bash", "/scripts/entrypoint.sh"]